// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rds_test.Data;

#nullable disable

namespace rds_test.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221027115736_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("rds_test.Models.Emp", b =>
                {
                    b.Property<int>("emp_num")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<bool>("admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("team")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("emp_num");

                    b.ToTable("emp");
                });

            modelBuilder.Entity("rds_test.Models.Suggestion", b =>
                {
                    b.Property<int>("case_num")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateOnly>("deadline")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("pdsa_act")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("pdsa_do")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("pdsa_plan")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("pdsa_study")
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("pic_after")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("pic_before")
                        .HasColumnType("longblob");

                    b.Property<string>("resdept")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("responsible")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("status")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("timeframe")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("title")
                        .HasColumnType("varchar(50)");

                    b.HasKey("case_num");

                    b.ToTable("suggestion");
                });
#pragma warning restore 612, 618
        }
    }
}
